import Link from "next/link";
import { phases } from "./../data/phases";

export default function Home(){
 const groups=[...new Set(phases.map(p=>p.group))];
 return <>
  <header className="site-nav"><div className="wrap nav"><Link className="brand" href="/">BOI<span>.</span></Link><nav className="links"><Link href="/research">Research</Link><Link href="/evidence">Evidence</Link><Link href="/about">About BOI</Link><a href="#method">Methodology</a><a href="#contact">Contact</a></nav></div></header>
  <main>
   <section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">Burundi Optimization & Intelligence</span><h1>Research infrastructure for complex problems.</h1><p>BOI develops computational research across optimization, artificial intelligence, data science, graph-based modelling and operations research, with applications in Burundi and emerging economies.</p><div className="actions"><Link className="btn primary" href="/research/project-1">Explore Project 1</Link><Link className="btn secondary" href="/about">About BOI</Link></div></div><aside className="hero-panel"><strong>Research status</strong><h2>Analytical baseline documented and reproducible.</h2><p>Project 1 is prepared for external technical review. Empirical validation and transport recalibration remain explicitly disclosed as incomplete.</p></aside></div></section>
   <section id="results" className="section"><div className="wrap"><div className="section-head"><span className="eyebrow">Public research record</span><h2>Evidence first. Claims stay proportional to the data.</h2><p>The public platform separates analytical results, secondary evidence and empirical validation so visitors can trace what has actually been observed, derived, modelled or assumed.</p></div><div className="metrics"><div className="metric"><b>72</b><span>market nodes in the BOI routing layer</span></div><div className="metric"><b>2,556</b><span>unique unordered market corridors</span></div><div className="metric"><b>10</b><span>agricultural products modelled</span></div><div className="metric"><b>44</b><span>documented research phases</span></div></div></div></section>
   <section className="section alt"><div className="wrap"><div className="project"><span className="eyebrow">Flagship research</span><h2>Graph-Based Combinatorial Optimization for Agricultural Supply Networks</h2><p>Project 1 studies agricultural supply networks as graph-based optimization problems, integrating market connectivity, transport sensitivity, corridor prioritization and multi-product allocation. The analytical model is documented and reproducible; external empirical validation remains a separate gate.</p><div><span className="tag">Combinatorial optimization</span><span className="tag">Graph algorithms</span><span className="tag">Network analysis</span><span className="tag">Agricultural supply chains</span><span className="tag">Operations research</span></div><div className="actions"><Link className="btn primary" href="/research/project-1">View full research record →</Link></div></div></div></section>
   <section id="method" className="section"><div className="wrap"><div className="section-head"><span className="eyebrow">Methodology</span><h2>A traceable research pipeline.</h2></div><div className="grid">{["Data provenance","Network modelling","Optimization","Sensitivity analysis","Validation gates","Reproducibility"].map((x,i)=><article className="card" key={x}><h3>{String(i+1).padStart(2,"0")} — {x}</h3><p>Documented methods, source provenance and explicit quality controls support reproducible research without overstating empirical certainty.</p></article>)}</div></div></section>
   <section className="section alt"><div className="wrap"><div className="section-head"><span className="eyebrow">Research process</span><h2>44 phases, organized into six scientific workstreams.</h2><p>The website exposes each phase as a traceable research record rather than a flat list of uploads.</p></div><div className="grid">{groups.map(g=><article className="card" key={g}><h3>{g}</h3><p>{phases.filter(p=>p.group===g).length} documented phases in this workstream.</p></article>)}</div></div></section>
   <section className="section"><div className="wrap"><div className="project"><span className="eyebrow">Public verification</span><h2>BOI can be independently inspected.</h2><p>Start with the organization profile, then move through the research portfolio, Project 1, methodology, data sources, validation, reproducibility and citation records.</p><div className="actions"><Link className="btn primary" href="/evidence">How to verify BOI →</Link><a className="btn secondary" href="https://github.com/Boi2026/burundi-optimization">GitHub repository</a><a className="btn secondary" href="https://www.linkedin.com/company/burundi-optimization-intelligence-boi/">LinkedIn</a></div></div></div></section>
   <section id="contact" className="section"><div className="wrap"><div className="project"><span className="eyebrow">Collaboration</span><h2>Research, data and technology partnerships.</h2><p>BOI is developing a platform for researchers, universities, technology organizations, development practitioners and data partners.</p><a className="btn primary" href="mailto:burundioptimizationintelligenc@gmail.com">Contact BOI</a></div></div></section>
  </main><footer className="footer"><div className="wrap footer-row"><span>© 2026 Burundi Optimization & Intelligence (BOI)</span><span>Research platform · Evidence-led · Reproducibility-first</span></div></footer>
 </>;
}
